import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Topbar from "@/components/Topbar";
import Footer from "@/components/Footer";
import Provider from "@/components/Provider";
import { Options } from "./api/auth/[...nextauth]/route";
import { getServerSession } from "next-auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "osac next app",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(Options);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
          <Topbar session={session} />
          <Navbar session={session} />
          {children}
          <div id="contact">
            <Footer />
          </div>
        </Provider>
      </body>
    </html>
  );
}
