import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Topbar from "@/components/Topbar";
import Footer from "@/components/Footer";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "osac next app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Topbar />
          <Navbar />
          {children}
          <div id="contact">
            <Footer />
          </div>
        </Provider>
      </body>
    </html>
  );
}
